apiVersion: v2
name: pagopa-afm-utils
description: Utility microservice for pagoPA AFM
type: application
version: 0.37.0
appVersion: 0.9.17
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
