apiVersion: v2
name: pagopa-afm-utils
description: Utility microservice for pagoPA AFM
type: application
version: 0.34.0
appVersion: 0.9.14
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
