apiVersion: v2
name: pagopa-afm-calculator-data
description: Microservice that handles calculation for pagoPA Advanced Fees Management
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
- name: microservice-chart
  version: 1.19.0
  repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
